# Generated by Django 2.2 on 2020-05-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='data_insercao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
