# Generated by Django 2.2 on 2020-05-13 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugestao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugestao',
            old_name='nome',
            new_name='estabelecimento',
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='data_insercao',
            field=models.DateField(verbose_name=datetime.date(2020, 5, 12)),
        ),
    ]
