# Generated by Django 2.2 on 2020-05-13 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugestao', '0002_auto_20200512_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='data_insercao',
            field=models.DateField(default=datetime.date(2020, 5, 12)),
        ),
    ]
