# Generated by Django 2.2 on 2020-05-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugestao', '0002_auto_20200512_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugestao',
            old_name='nome',
            new_name='estabelecimento',
        ),
    ]
