# Generated by Django 2.2 on 2020-05-13 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugestao', '0003_auto_20200512_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='data_insercao',
            field=models.DateField(default=datetime.date(2020, 5, 13)),
        ),
    ]
