# Generated by Django 2.2 on 2020-05-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_categoria'),
        ),
    ]
