# Generated by Django 2.2 on 2020-05-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='foto',
        ),
    ]
