# Generated by Django 2.2 on 2020-05-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0002_auto_20200505_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='celular',
            field=models.CharField(max_length=11),
        ),
    ]
