# Generated by Django 2.2 on 2020-05-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0003_auto_20200505_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
