# Generated by Django 2.2 on 2020-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0005_estabelecimento_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='celular',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='site',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
